// frontend/src/app/layout.jsx

// import { ExtensionErrorHandler } from "@/components/utils/error-handler";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ExtensionErrorHandler } from "@/components/utils/error-handler";
import { StoreProvider } from "@/providers/store-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fantasy Coach",
  description: "Generated by create next app",
};

import ErrorBoundary from "@/components/shared/error-boundary";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, viewport-fit=cover"
        />
      </head>
      {/* Initialize in your root layout */}
      {ExtensionErrorHandler.init()}
      <body
        className="bg-background text-foreground antialiased"
        suppressHydrationWarning
      >
        <StoreProvider>
          <ErrorBoundary>
            {children}
          </ErrorBoundary>
        </StoreProvider>
      </body>
    </html>
  );
}
